### ISSUE TITLE
nix_nixos should support config expressions as well as files

### ISSUE THREAD

**Issue by ocharles** [andrewchambers/terraform-provider-nix#10]
I'm currently using `local_file`, but it'd really be easier if I could just give `nix_nixos` a `configuration.nix` expression:

```hcl
resource "nix_nixos" "foo" {
  configuration = <<EOT
  { .. }
  EOT
}
```

**Comment by andrewchambers** [comment]
Should be pretty easy to support.

**Comment by andrewchambers** [comment]
I wonder if having only expressions would be better. If you need a file you can always do an expression as "import ./file.nix". I will have a think about it.

**Comment by andrewchambers** [comment]
It might be slightly trickier than I thought, nixos-rebuild doesn't seem to take expressions for config - so we could send them a patch, and maybe work around by writing a temporary file for each config expression. The main problem is the temporary files can't be in /tmp/ as they need to be in the working dir for relative paths to work properly.

**Comment by ocharles** [comment]
Ahh, that's a good point. So maybe `local_file` is the way to go...

**Comment by ocharles** [comment]
OTOH, we could imagine 

```hcl
resource "nix_nixos" "foo" {
  configuration = <<EOT
  EOT
  working_dir = "/any/path/here";
}
```

`configuration` would then create a file in the given `working_dir` for use with `nixos-rebuild`.

**Comment by andrewchambers** [comment]
relative to the current terraform file would be okay, not too sure how to ensure that though.

**Comment by andrewchambers** [comment]
@ocharles ok, new idea... if configuration_path AND configuration are both set, it means to write the config/build expression to disk at that location, otherwise just read it. I think that resolves the problem.

I think I will prototype it tomorrow.

**Comment by andrewchambers** [comment]
Ok, this is implemented, you will need to update your config to try it, but the change is quite simple. 

You need to change nixos_config to nixos_config_path. Now nixos_config can be used for inline configuration, and the generated config will be written to nixos_config_path. 

If you don't need inline config, you just don't specify it and the behavior is the same as before.

**Comment by ocharles** [comment]
That sounds good to me! Thanks for your work on this, Terraform is starting
to look very viable!
