### ISSUE TITLE
rework

### ISSUE THREAD

**Issue by andrewchambers** [andrewchambers/terraform-provider-nix#4]
This project is being reworked and simplified, stay tuned.

**Comment by memberbetty** [comment]
@andrewchambers What's the status of the project? Your approach seems good.

**Comment by andrewchambers** [comment]
I didn't have time to work on it unfortunately, It is something I want to be improved, but don't have time just yet. The main simplification is that 'nixos-rebuild' already supports installing to remote machines, so things would ideally just use that.

**Comment by andrewchambers** [comment]
I will try to fix this up in the next week or two. I think this project is worthwhile.

**Comment by andrewchambers** [comment]
@memberbetty  I have rewritten the plugin, it is more flexible, and much better now. Let me know if it matches what you need :)

**Comment by memberbetty** [comment]
Can it deploy to a private VPC?

**Comment by andrewchambers** [comment]
It can deploy to anything you can ssh to. I tested with google cloud platform.

**Comment by memberbetty** [comment]
Thanks, I will consider this as an option for future projects. I did notice some spelling errors in your example, which is something that makes something that technically seems quite good less appealing for new people. Please go over it again if that's something you consider to be important. 

Overall, I consider this good work.

**Comment by andrewchambers** [comment]
Will do, thanks for the feedback.
