### ISSUE TITLE
Can't use provider with local file

### ISSUE THREAD

**Issue by ocharles** [andrewchambers/terraform-provider-nix#7]
Here is my rough plan:

```hcl
resource "local_file" "configuration" {
  content = "{ imports = ${path.root}/nix/configuration.nix; }"
  filename = "${path.root}/derived/nixos/machine.nix"
}

resource "nix_nixos" "deployment" {
  nixos_config = local_file.configuration.filename
}
```

The idea is I can write a normal NixOS configuration file, and expose it as a NixOS module that can be configured based on other Terraform resources. For example, `nix/configuration.nix` might be something like

```nixos
{
  options = { databaseServer = ... };
  config = { ... };
}
```

Now in Terraform I can do something like this:

```
resource "local_file" "configuration" {
  content = "{ imports = ${path.root}/nix/configuration.nix; databaseServer = "${aws_instance.database.ip }"` }"
  filename = "${path.root}/derived/nixos/machine.nix"
}
```

To configure a server to talk to a Terraform-created database server.

However, this doesn't work because this resource needs the file to exist at plan time, but the file is only created during apply time. 

I wonder if treating the Nix store path as computed instead could work here?

**Comment by andrewchambers** [comment]
This is definitely something I would like to support, thanks for pointing it out - I will try to reproduce and make it work when I have some time.

**Comment by andrewchambers** [comment]
This should be fixed now, reopen if you have issues.

**Comment by ocharles** [comment]
Works perfectly, thank you!
